### ISSUE TITLE
client is not thread safe

### ISSUE THREAD

**Issue by dwburke** [liquidweb/go-lwApi#8]
https://lw.slack.com/archives/C02KW0VUH/p1559679680030900

**Comment by ctriv** [comment]
The same http.Header map is passed to each request by reference.  It is possible to get concurrent access on this map if you have multiple goroutines sending requests.

Do we even needs this header map in the client object?  The attribute is public, is there code that is using it?

**Comment by ctriv** [comment]
Looking at the git history, it's clear that the Headers field is an intended feature.  I'm working on a PR to make it threadsafe.
